# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NEEducation' do
  use_frameworks!
  pod 'NEEducationSDK', :path => 'NEEducationSDK'

  target 'NEEducationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NEEducationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
